name: Makefile CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest   
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: make install
    - name: Build
      run: make
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'dist'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
